### ISSUE TITLE
How to enable(re-start) and disable(stop) the streaming on the fly.

### ISSUE THREAD

**Issue by ServeurpersoCom** [Dregu/visio#5]
Hello,

What is the clean way to enable(re-start) and disable(stop) the streaming on the fly ?

Thanks,
Pascal

**Comment by Dregu** [comment]
I dunno, figure it out

Thanks.

**Comment by ServeurpersoCom** [comment]
I work on this myself if you are interested for visio

**Comment by ServeurpersoCom** [comment]
Solved : it's easy as ws.close and re-open:)
I reworked the code to permit this (we must disable the auto-reconnect before the close)
